name: pt_mert
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_auth: ^5.6.2

  user_repository:
    path: packages/user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo_Condensed-Thin.ttf
          weight: 100
        - asset: assets/fonts/Archivo_Condensed-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Archivo_Condensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Archivo_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo_Condensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Archivo_Condensed-ExtraBold.ttf
          weight: 800