// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmd4hjzuXP3FXQ6_NAJ-XuONvOIEhzFNM',
    appId: '1:979584192014:web:37d67d9a79c8fd4c91765f',
    messagingSenderId: '979584192014',
    projectId: 'ptmert-cffcb',
    authDomain: 'ptmert-cffcb.firebaseapp.com',
    storageBucket: 'ptmert-cffcb.firebasestorage.app',
    measurementId: 'G-TC08EFS87J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERofxiKw4ERpLdu3kf9Wo-9Wvzij-nCk',
    appId: '1:979584192014:android:b113e6ab4955f34791765f',
    messagingSenderId: '979584192014',
    projectId: 'ptmert-cffcb',
    storageBucket: 'ptmert-cffcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVmoGpnDuXUyVWA7U-VQKZDxy_5oHHjIE',
    appId: '1:979584192014:ios:bdce85bd2c11919791765f',
    messagingSenderId: '979584192014',
    projectId: 'ptmert-cffcb',
    storageBucket: 'ptmert-cffcb.firebasestorage.app',
    iosBundleId: 'com.artyom.ptMert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVmoGpnDuXUyVWA7U-VQKZDxy_5oHHjIE',
    appId: '1:979584192014:ios:2d7b24a9c73394b991765f',
    messagingSenderId: '979584192014',
    projectId: 'ptmert-cffcb',
    storageBucket: 'ptmert-cffcb.firebasestorage.app',
    iosBundleId: 'com.example.ptMert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmd4hjzuXP3FXQ6_NAJ-XuONvOIEhzFNM',
    appId: '1:979584192014:web:5c5b65be9734fba091765f',
    messagingSenderId: '979584192014',
    projectId: 'ptmert-cffcb',
    authDomain: 'ptmert-cffcb.firebaseapp.com',
    storageBucket: 'ptmert-cffcb.firebasestorage.app',
    measurementId: 'G-MN80XTRG55',
  );
}
