name: transaction_repository
description: "Dart package which manages the transactions."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.1
  equatable: ^2.0.7
  cloud_firestore: ^5.6.11
  uuid: ^4.5.1

  user_repository:
    path: ../user_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
